#!/usr/bin/env bash

cd ..

if [ -d claude-usage-extension ]; then
	rm -rf ~/.local/share/gnome-shell/extensions/claude-code-usage@saralray
	cp -r claude-usage-extension ~/.local/share/gnome-shell/extensions/claude-code-usage@saralray 
	cd ~/.local/share/gnome-shell/extensions/claude-code-usage@saralray/schemas
	glib-compile-schemas .
	gnome-session-quit --no-prompt
else
	echo "Extension folder not found"
fi
